Vagrant.configure("2") do |config|
    
    config.vm.define "api" do |api|
        api.vm.box = "precise64"
        api.vm.box_url = "http://files.vagrantup.com/precise64.box"
        api.vm.provision :shell, :path => "api-bootstrap.sh"
        api.vm.network :private_network, ip: "10.10.10.31"
        api.vm.network "forwarded_port", guest: 80, host: 80
        api.vm.hostname = "api"
        
        api.vm.provider :virtualbox do |vb|
            vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
            vb.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
