Vagrant.configure("2") do |config|
    
    config.vm.define "api" do |api|
        api.vm.box = "precise64"
        api.vm.box_url = "http://files.vagrantup.com/precise64.box"
        api.vm.provision :shell, :path => "api-bootstrap.sh"
        api.vm.network :private_network, ip: "10.10.10.31"
        api.vm.hostname = "api"
       config.vm.synced_folder "../../backend/code/var/api", "/var/www/api",  owner: "www-data", group: "www-data"
        
        api.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
