Vagrant.configure("2") do |config|
    
    config.vm.provision "shell", inline: "echo Provisioning Archiver appliance"

    #setup elastic search boxes
    config.vm.define "es1" do |es1|
        es1.vm.box = "precise64"
        es1.vm.box_url = "http://files.vagrantup.com/precise64.box"
        es1.vm.provision :shell, :path => "es-bootstrap.sh"
        es1.vm.network :private_network, ip: "10.10.10.10"
        es1.vm.hostname = "es1"
        es1.vm.network "forwarded_port", guest: 9200, host: 9200

        es1.vm.provider :virtualbox do |vbes1|
            vbes1.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    config.vm.define "es2" do |es2|
        es2.vm.box = "precise64"
        es2.vm.box_url = "http://files.vagrantup.com/precise64.box"
        es2.vm.provision :shell, :path => "es-bootstrap.sh"
        es2.vm.network :private_network, ip: "10.10.10.11"
        es2.vm.hostname = "es2"
       
        es2.vm.provider :virtualbox do |vbes2|
            vbes2.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    config.vm.define "es3" do |es3|
        es3.vm.box = "precise64"
        es3.vm.box_url = "http://files.vagrantup.com/precise64.box"
        es3.vm.provision :shell, :path => "es-bootstrap.sh"
        es3.vm.network :private_network, ip: "10.10.10.12"
        es3.vm.hostname = "es3"
        
        es3.vm.provider :virtualbox do |vbes3|
            vbes3.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    #setup gluster boxes

    config.vm.define "gfs1" do |gfs1|
        gfs1.vm.box = "precise64"
        gfs1.vm.box_url = "http://files.vagrantup.com/precise64.box"
        gfs1.vm.provision :shell, :path => "gfs-bootstrap.sh"
        gfs1.vm.network :private_network, ip: "10.10.10.20"
        gfs1.vm.hostname = "gfs1"

        gfs1.vm.provider :virtualbox do |vbgfs1|
            vbgfs1.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    config.vm.define "gfs2" do |gfs2|
        gfs2.vm.box = "precise64"
        gfs2.vm.box_url = "http://files.vagrantup.com/precise64.box"
        gfs2.vm.provision :shell, :path => "es-bootstrap.sh"
        gfs2.vm.network :private_network, ip: "10.10.10.21"
        gfs2.vm.hostname = "gfs2"
       
        gfs2.vm.provider :virtualbox do |vbgfs2|
            vbgfs2.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    config.vm.define "gfs3" do |gfs3|
        gfs3.vm.box = "precise64"
        gfs3.vm.box_url = "http://files.vagrantup.com/precise64.box"
        gfs3.vm.provision :shell, :path => "es-bootstrap.sh"
        gfs3.vm.network :private_network, ip: "10.10.10.22"
        gfs3.vm.hostname = "gfs3"
        
        gfs3.vm.provider :virtualbox do |vbgfs3|
            vbgfs3.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end

    config.vm.define "api" do |api|
        api.vm.box = "precise64"
        api.vm.box_url = "http://files.vagrantup.com/precise64.box"
        api.vm.provision :shell, :path => "es-bootstrap.sh"
        api.vm.network :private_network, ip: "10.10.10.30"
        api.vm.hostname = "api"
        
        api.vm.provider :virtualbox do |vbapi|
            vbapi.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end