<?php
return array(
    'levels' => array(
        '1'=>array('plan_name'=>'Free', 'ratlimit'=>5,'ttlmin'=>1,'urlto'=>false, 'emailto'=>false),
        '2'=>array('plan_name'=>'Paid', 'ratlimit'=>100,'ttlmin'=>1,'urlto'=>false, 'emailto'=>true),
        '3'=>array('plan_name'=>'Pro', 'ratlimit'=>500,'ttlmin'=>5,'urlto'=>true, 'emailto'=>true),
        '4'=>array('plan_name'=>'Corp', 'ratlimit'=>1000,'ttlmin'=>5,'urlto'=>true, 'emailto'=>true)
    ),
    'defaults' => array(
        'crontab'=>'0 0 * * *',
        'allow'=>86399,
        'min_allow'=>300
    )'levels' => array(
    '1'=>array('plan_name'=>'Free', 'ratlimit'=>5,'ttlmin'=>1,'urlto'=>false, 'emailto'=>false),
    '2'=>array('plan_name'=>'Paid', 'ratlimit'=>100,'ttlmin'=>1,'urlto'=>false, 'emailto'=>true),
    '3'=>array('plan_name'=>'Pro', 'ratlimit'=>500,'ttlmin'=>5,'urlto'=>true, 'emailto'=>true),
    '4'=>array('plan_name'=>'Corp', 'ratlimit'=>1000,'ttlmin'=>5,'urlto'=>true, 'emailto'=>true)
),
                'defaults' => array(
    'crontab'=>'0 0 * * *',
    'allow'=>86399,
    'min_allow'=>300
)
    'fileroom' => array(
        'folder' => array(
            'example' => 'SHMOE_JOE_1234',
            'autogenerated' => false,
            'required' => true
        ),
        'doc_uri' => array(
            'example' => 'https://fbg.com/data/SHMOE_JOE_1234/398196',
            'autogenerated' => true,
            'required' => true
        ),
        'doc_type' => array(
            'example' => 'letter',
            'autogenerated' => false,
            'required' => false
        ),
        'doc_group' => array(
            'example' => 'Psychological Therapy Folder',
            'autogenerated' => false,
            'required' => false
        ),
        'doc_date' => array(
            'example' => '10/16/12',
            'autogenerated' => false,
            'required' => false
        ),
        'cc' => array(
            'example' => array("Joe Bro", "Sam Low"),
            'autogenerated' => false,
            'required' => false
        ),
        'doc_location' => array(
            'example' => 'San Mateo',
            'autogenerated' => false,
            'required' => false
        ),
        'text' => array(
            'example' => 'this is some example OCR which doesn\'t mean anything',
            'autogenerated' => true,
            'required' => false
        )
    )
);

