require 'yaml'

vconfig = YAML::load_file("../config/vagrant_config.yml")

Vagrant.configure("2") do |config|
    
    config.vm.define "monitor" do |monitor|
        monitor.vm.box = "precise64"
        monitor.vm.box_url = "http://files.vagrantup.com/precise64.box"
        monitor.vm.provision :shell, :path => "monitor-bootstrap.sh"
        monitor.vm.network :private_network, ip: "10.10.10.41"
        monitor.vm.hostname = "monitor"
        
        config.vm.synced_folder "../config", "/var/config",  owner: "root", group: "root"
        
        monitor.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", vconfig['fbg']['memory']]
        end
    end
end
