Vagrant.configure("2") do |config|
    
    config.vm.define "monitor" do |monitor|
        monitor.vm.box = "precise64"
        monitor.vm.box_url = "http://files.vagrantup.com/precise64.box"
        monitor.vm.provision :shell, :path => "monitor-bootstrap.sh"
        monitor.vm.network :private_network, ip: "10.10.10.41"
        monitor.vm.hostname = "monitor"
        monitor.vm.network "forwarded_port", guest: 80, host: 8080
                
        monitor.vm.provider :virtualbox do |vb|
            vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
            vb.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
