require 'yaml'

vconfig = YAML::load_file("../../config/common/vagrant.yml")

Vagrant.configure("2") do |config|
    
    config.vm.define vconfig['monitor_name'] do |bx|
        bx.vm.box = "precise64"
        bx.vm.box_url = "http://files.vagrantup.com/precise64.box"
        bx.vm.provision :shell, :path => "monitor-bootstrap.sh"
        bx.vm.network "public_network", bridge: vconfig['eth'], ip: vconfig['monitor_ip']
        bx.vm.hostname = vconfig['monitor_name']
        
        bx.vm.synced_folder "../../config", "/var/config",  owner: "root", group: "root"
        
        bx.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", 512]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end
end
