Vagrant.configure("2") do |config|
    
    config.vm.define "es1" do |es1|
        es1.vm.box = "precise64"
        es1.vm.box_url = "http://files.vagrantup.com/precise64.box"
        es1.vm.provision :shell, :path => "es-bootstrap-es1.sh"
        es1.vm.network :private_network, ip: "10.10.10.11"
        es1.vm.hostname = "es1"

        config.vm.synced_folder "../config", "/var/config",  owner: "root", group: "root"

        es1.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
    end
end
