Vagrant.configure("2") do |config|
    
    config.vm.define "es2" do |es2|
        es2.vm.box = "precise64"
        es2.vm.box_url = "http://files.vagrantup.com/precise64.box"
        es2.vm.provision :shell, :path => "es-bootstrap-es2.sh"
        es2.vm.network :private_network, ip: "10.10.10.12"
        es2.vm.hostname = "es2"

        config.vm.synced_folder "../config", "/var/config",  owner: "root", group: "root"

        es2.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
        end
    end
end
