Vagrant.configure("2") do |config|
        config.vm.box = "precise64"
        config.vm.box_url = "http://files.vagrantup.com/precise64.box"
        config.vm.provision :shell, :path => "bootstrap.sh"
        config.vm.network "public_network"
        config.vm.hostname = "fbg"
                
        config.vm.synced_folder "../backend/code/var/api", "/var/www/api",  owner: "www-data", group: "www-data"

        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", 4096]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
end
