Vagrant.configure("2") do |config|
        config.vm.box = "precise64"
        config.vm.box_url = "http://files.vagrantup.com/precise64.box"
        config.vm.provision :shell, :path => "bootstrap.sh"
        config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "forwarded_port", guest: 9200, host: 19200
	config.vm.network "forwarded_port", guest: 3306, host: 13306
	config.vm.network "private_network", ip: "10.10.10.101"
        config.vm.hostname = "fbg"
                
        config.vm.synced_folder "../backend/code/var/api", "/var/www/api",  owner: "www-data", group: "www-data"

        config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", 2048]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
end
