require 'yaml'

vconfig = YAML::load_file("../../config/common/vagrant.yml")

Vagrant.configure("2") do |config|
    
    config.vm.define vconfig['gfs1_name'] do |bx|
        bx.vm.box = "precise64"
        bx.vm.box_url = "http://files.vagrantup.com/precise64.box"
        bx.vm.provision :shell, :path => "gfs-bootstrap-gfs1.sh"
        bx.vm.network "public_network", bridge: vconfig['eth'], ip: vconfig['gfs1_ip']
        #bx.vm.network :private_network, ip: "10.10.10.21"
        bx.vm.hostname = vconfig['gfs1_name']
        
        bx.vm.synced_folder "../../config", "/var/config",  owner: "root", group: "root"
        
        bx.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", vconfig['memory']]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end
end
