Vagrant.configure("2") do |config|
    
    config.vm.define "gfs1" do |gfs1|
        gfs1.vm.box = "precise64"
        gfs1.vm.box_url = "http://files.vagrantup.com/precise64.box"
        gfs1.vm.provision :shell, :path => "gfs-bootstrap-gfs1.sh"
        gfs1.vm.network :private_network, ip: "10.10.10.21"
        gfs1.vm.hostname = "gfs1"
        
        config.vm.synced_folder "../config", "/var/config",  owner: "root", group: "root"
        
        gfs1.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
        end
    end
end
