require 'yaml'

vconfig = YAML::load_file("../config/vagrant_config.yml")

Vagrant.configure("2") do |config|
    
    config.vm.define "es3" do |es3|
        es3.vm.box = "precise64"
        es3.vm.box_url = "http://files.vagrantup.com/precise64.box"
        es3.vm.provision :shell, :path => "es-bootstrap-es3.sh"
        es3.vm.network :private_network, ip: "10.10.10.13"
        es3.vm.hostname = "es3"
        
        config.vm.synced_folder "../config", "/var/config",  owner: "root", group: "root"
        
        es3.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", vconfig['fbg']['memory']]
        end
    end
end
