Vagrant.configure("2") do |config|
    config.vm.box = "presize"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.provision :shell, :path => "es-bootstrap.sh"
    config.vm.network :private_network, ip: "10.10.10.12"
    config.vm.hostname = "es3"
    #config.vm.network "forwarded_port", guest: 9200, host: 9200

    config.vm.provider :virtualbox do |vb|
        vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
end
